name: PowerShell Lint

on:
  push:
    paths:
      - "**/*.ps1"
      - "**/*.psm1"
  pull_request:
    paths:
      - "**/*.ps1"
      - "**/*.psm1"

jobs:
  lint:
    name: PowerShell Script Linting
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -AllowClobber

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $errorFound = $false
          $files = Get-ChildItem -Path . -Recurse -Include *.ps1, *.psm1 -File
          foreach ($file in $files) {
            Write-Host "Linting $($file.FullName)"
            $results = Invoke-ScriptAnalyzer -Path $file.FullName -Severity Error
            if ($results.Count -gt 0) {
              $errorFound = $true
              Write-Host "Errors in $($file.FullName):"
              $results | Format-Table -AutoSize
            }
          }
          if ($errorFound) {
            Write-Error "PSScriptAnalyzer found one or more errors."
            exit 1
          }
